apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hapi-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hapi-cronjob
              image: ${DOCKER_REGISTRY}/${IMAGE_NAME_HAPI}:${VERSION}
              args:
                - /bin/sh
                - -c
                - /usr/bin/node /opt/application/src/libs/sync-bps.js; /usr/bin/node /opt/application/src/libs/sync-proxies.js
              env:
                - name: DB_HOST
                  value: "${DB_HOST}"
                - name: DB_NAME
                  value: "${DB_NAME}"
                - name: DB_PASSWORD
                  value: "${DB_PASSWORD}"
                - name: DB_PORT
                  value: "${DB_PORT}"
                - name: DB_SCHEMA
                  value: "${DB_SCHEMA}"
                - name: DB_USER
                  value: "${DB_USER}"
                - name: EOS_API_ENDPOINT
                  value: https://api.eosio.cr
                - name: VIRTUAL_HOST
                  value: 0.0.0.0
                - name: VIRTUAL_PORT
                  value: "9090"
          restartPolicy: Never
