name: Push code to staging environment

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
    - name: run push
      run: |
        export SSH_PRV_KEY=`echo "${{secrets.SSH_PRV_KEY}}"`
        make push-staging
