name: Push code to staging environment

on:
  push:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: run push
      run: |
        echo "Pushing to branch 'staging'"
        remote_repo="ssh://${{secrets.USER}}@apps.eosio.cr/var/repo/eos-rate.git"
        echo ${{secrets.PRIVATE_KEY}} > id_rsa
        PKEY=id_rsa git push "$remote_repo" HEAD:staging

